name: CI
on:
  push:
    branches: ['**'] # Run on all branches, all commits
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: read

# Prevent concurrent runs for the same commit
concurrency:
  group: ci-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            shared: &common
              - 'packages/shared/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - '.github/workflows/**'
              - '.github/actions/**'
            redirector:
              - *common
              - 'packages/redirector/**'
            assets:
              - *common
              - 'packages/assets/**'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: pnpm check:ci

  test:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
        exclude:
          - package: shared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: pnpm --filter ${MATRIX_PACKAGE} test
        env:
          MATRIX_PACKAGE: ${{ matrix.package }}

  all-tests:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.test.result }}" == "failure" || "${{ needs.test.result }}" == "cancelled" ]]; then
            exit 1
          fi
